### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Thanh-Binh** [yuezhihan/ts2vec#10]
I run
python3 train.py ETTm1 mytest --loader forecast_csv

and have got an error as follows.
Could you pls help me? thanks
##############################
Dataset: ETTm1
Arguments: Namespace(batch_size=8, dataset='ETTm1', epochs=None, eval=False, gpu=0, irregular=0, iters=None, loader='forecast_csv', lr=0.001, max_threads=None, max_train_length=3000, repr_dims=320, run_name='binh', save_every=None, seed=None)
Loading data... done
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    loss_log = model.fit(
  File "/home/binh/experiments/ts2vec/ts2vec.py", line 137, in fit
    loss.backward()
  File "/home/binh/.local/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/binh/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA out of memory. Tried to allocate 380.00 MiB (GPU 0; 3.82 GiB total capacity; 1.80 GiB already allocated; 254.62 MiB free; 2.25 GiB reserved in total by PyTorch)

**Comment by fffii** [comment]
How did you solve it
